apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: s3read
  name: s3read
spec:
  serviceAccountName: s3access 
  containers:
  - command:
    - sleep
    - "3000"
    image: amazon/aws-cli:latest
    name: s3read
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
